### ISSUE TITLE
WE NEEEEEEED YOU

### ISSUE THREAD

**Issue by simonomi** [patrickmelville/simon-game#1]
You're not here we're sending out the bat signal I have not much time I have to go come back we need you!!!!!!!!!!!!

**Comment by patrickmelville** [comment]
im so sorry. ive been kidnapped and sent do a different location. I am unable to return. I hope everything is going well. Let me know if you need anything.

**Comment by simonomi** [comment]
Well, good luck in your new location. By the way... you should check out coding royale, it's received a new update to v2.2 (check it out).

**Comment by patrickmelville** [comment]
Awesome. I will
